import { Locations } from "./types";

const LocationData: Locations[] = [
    {label: 'Sydney Opera House', city: 'Sydney', country: 'Australia', rating: 7},
    {label: 'Kinokuniya', city: 'Sydney', country: 'Australia', rating: 10},
    {label: 'QVB', city: 'Sydney', country: 'Australia', rating: 2},
    {label: 'Bondi-Coogee Walk', city: 'Sydney', country: 'Australia', rating: 4},
    {label: 'Antarctica', city: 'NA', country: 'Antarctica', rating: -99},
    {label: 'DOPA', city: 'Sydney', country: 'Australia', rating: 9},
    {label: 'Pha that luang', city: 'Vientiane', country: 'Laos', rating: 6.9},
    {label: 'Kinokuniya', city: 'Sydney', country: 'Australia', rating: 10},
    {label: 'QVB', city: 'Sydney', country: 'Australia', rating: 7},
    {label: 'Sydney Opera House', city: 'Sydney', country: 'Australia', rating: 7},
    {label: 'Kinokuniya', city: 'Sydney', country: 'Australia', rating: 10},
    {label: 'QVB', city: 'Sydney', country: 'Australia', rating: 7},
    {label: 'Sydney Opera House', city: 'Sydney', country: 'Australia', rating: 7},
    {label: 'Kinokuniya', city: 'Sydney', country: 'Australia', rating: 10},
    {label: 'QVB', city: 'Sydney', country: 'Australia', rating: 7},
    {label: 'Sydney Opera House', city: 'Sydney', country: 'Australia', rating: 7},
    {label: 'Kinokuniya', city: 'Sydney', country: 'Australia', rating: 10},
    {label: 'QVB', city: 'Sydney', country: 'Australia', rating: 7},
    {label: 'Sydney Opera House', city: 'Sydney', country: 'Australia', rating: 7},
    {label: 'Kinokuniya', city: 'Sydney', country: 'Australia', rating: 10},
    {label: 'QVB', city: 'Sydney', country: 'Australia', rating: 7},
    {label: 'Sydney Opera House', city: 'Sydney', country: 'Australia', rating: 7},
    {label: 'Kinokuniya', city: 'Sydney', country: 'Australia', rating: 10},
    {label: 'QVB', city: 'Sydney', country: 'Australia', rating: 7},
    {label: 'Sydney Opera House', city: 'Sydney', country: 'Australia', rating: 7},
    {label: 'Kinokuniya', city: 'Sydney', country: 'Australia', rating: 10},
    {label: 'QVB', city: 'Sydney', country: 'Australia', rating: 7},
    {label: 'Sydney Opera House', city: 'Sydney', country: 'Australia', rating: 7},
    {label: 'Kinokuniya', city: 'Sydney', country: 'Australia', rating: 10},
    {label: 'QVB', city: 'Sydney', country: 'Australia', rating: 7},
    {label: 'Sydney Opera House', city: 'Sydney', country: 'Australia', rating: 7},
    {label: 'Kinokuniya', city: 'Sydney', country: 'Australia', rating: 10},
    {label: 'QVB', city: 'Sydney', country: 'Australia', rating: 7},
];

export default LocationData;