import { Locations } from "./types";

const LocationData: Locations[] = [
    {label: 'Sydney Opera House', city: 'Sydney', country: 'Australia', rating: 7},
    {label: 'Kinokuniya', city: 'Sydney', country: 'Australia', rating: 10},
    {label: 'QVB', city: 'Sydney', country: 'Australia', rating: 2},
    {label: 'Bondi-Coogee Walk', city: 'Sydney', country: 'Australia', rating: 4},
    {label: 'Antarctica', city: 'NA', country: 'Antarctica', rating: -99},
    {label: 'DOPA', city: 'Sydney', country: 'Australia', rating: 9},
    {label: 'Pha that luang', city: 'Vientiane', country: 'Laos', rating: 6.9},
    {label: 'Circular Quay', city: 'Sydney', country: 'Australia', rating: 1},
    {label: 'Myeongdong Market', city: 'Seoul', country: 'South Korea', rating: 9.9},
    {label: 'DMZ', city: 'Panmumjon', country: 'Korea', rating: 7},
    {label: 'Fortress', city: 'Sydney', country: 'Australia', rating: 8},
    {label: 'State Library of NSW', city: 'Sydney', country: 'Australia', rating: 4},
    {label: 'Catmosphere', city: 'Surry Hills', country: 'Australia', rating: 7.2},
    {label: 'teamlab Planets', city: 'Tokyo', country: 'Japan', rating: 10},
    {label: 'Exhibition Centre', city: 'Darling Harbour', country: 'Australia', rating: 5},
    {label: 'Sydney Opera House', city: 'Sydney', country: 'Australia', rating: 7},
    {label: 'Royal National Park', city: 'Heathcote', country: 'Australia', rating: 1},
    {label: 'Sentosa Island', city: 'Sentosa', country: 'Singapore', rating: 7},
    {label: 'Chinatown Sydney', city: 'Haymarket', country: 'Australia', rating: 6},
    {label: 'Gacha+ Cafe', city: 'Sydney', country: 'Australia', rating: 7.5},
    {label: 'Changi Village', city: 'Changi Village', country: 'Singapore', rating: 4},
    {label: 'Hakken! (Plaza SG)', city: 'Dhoby Ghaut', country: 'Singapore', rating: 8},
    {label: 'Tuas Checkpoint', city: 'Tuas', country: 'Singapore', rating: 0},
    {label: 'Marina Bay Sands', city: 'Marina Bay', country: 'Singapore', rating: 66},
    {label: 'Hong Kong Island', city: 'HK', country: 'HK', rating: 7},
    {label: 'Borobudder', city: 'Yogyakarta', country: 'Indonesia', rating: 6.2},
    {label: 'Bugis Junction', city: 'Bugis', country: 'Singapore', rating: 5.3},
    {label: 'Sydney Karoake', city: 'Sydney', country: 'Australia', rating: 6.5},
    {label: 'Noodle King', city: 'Haymarket', country: 'Australia', rating: 7.9},
    {label: 'Machi Machi', city: 'Sydney', country: 'Australia', rating: 7},
    {label: 'Angkor Wat', city: 'Siem Reap', country: 'Laos', rating: 7},
    {label: 'Central Plaza', city: 'Jakarta', country: 'Indonesia', rating: 4},
    {label: 'Meriton Suites', city: 'Sydney', country: 'Australia', rating: 8},
];

export default LocationData;